language: scala
scala:
   - 2.11.12
sudo: false
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
notifications:
  email:
    recipients:
      - jahagirdar.ro@husky.neu.edu
      - chugh.k@husky.neu.edu
  on_success: always
  on_failure: always
